[profiles.consulting.groups.julia_zubel_profile]
keywords = [
    "data engineer",
    "junior data engineer",
    "data expert",
    "sql server",
    "t-sql",
    "ssms",
    "elt",
    "etl developer",
    "data warehouse",
    "financial data",
    "finance data analyst",
    "vba",
    "excel automation",
    "power bi",
    "azure data",
    "python developer",
    "pandas",
    "numpy",
    "spark",
    "docker",
    "junior data analyst",
    "big data",
    "business data analyst",
    "reporting analyst",
    "it support",
]
